[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-function-docstring", 
    "too-many-arguments",
    "too-many-positional-arguments",
    "global-statement",
    "unused-import",
    "unused-variable",
    "import-error"
]

[tool.pylint.format]
max-line-length = 100